export { isNIK } from './isNIK.js'
export { isNPWP } from './isNPWP.js'
export { isPhone } from './isPhone.js'
export { isEmail } from './isEmail.js'
export { isURL } from './isURL.js'
export { parseNIK } from './parseNIK.js'
export type { NIKInfo } from './parseNIK.js'
export { isPlatNomor } from './isPlatNomor.js'
export { isKodepos } from './isKodepos.js'
export { isNoRekening } from './isNoRekening.js'
export { isNoSIM } from './isNoSIM.js'
export { isPassport } from './isPassport.js'
export { isNoBPJS } from './isNoBPJS.js'
export { isNoKK } from './isNoKK.js'
